In [4]:
import numpy as np
#import de mes fonction d'activation ,ici avec Relu
X=np.array([[1,1],[2,2],[3,3]])
W1=np.array([[1,2],[3,4],[5,6]])
b1=np.array([1,1,1])
#creation de la premiere couche avec deux neurones
Z1=np.dot(X,W1.T)+b1
#print(f"Z1=\n{Z1}")




Application de fonction d'activation ReLU


In [6]:
import sys
sys.path.append("../04-fonctions-activation")
from relu import Relu as rl

A1=rl(Z1)
print(f"Relu(Z1)=\n{A1}")


Relu(Z1)=
[[ 4  8 12]
 [ 7 15 23]
 [10 22 34]]


In [7]:
#calculs de la deuxiem couche (premiaire couche cache)
W2=np.array([[1,2,3],[4,5,6]])
b2=np.array([1,1])
Z2=np.dot(A1,W2.T)+b2
print(f"Z2=\n{Z2}")
#application de relu sur le premiaire couche cache
A2=rl(Z2)
print(f"Relu(Z2)=\n{A2}")

Z2=
[[ 57 129]
 [107 242]
 [157 355]]
Relu(Z2)=
[[ 57 129]
 [107 242]
 [157 355]]


In [8]:

#calculs de la troisieme couche et sortie ,vue qu'on est regression ,ici pas de fonction d'activation ici
W3=np.array([[1,2]])
b3=np.array([1])
Z3=np.dot(A2,W3.T)+b3
print(f"la prediction du reseaux est :\n{Z3}")




la prediction du reseaux est :
[[316]
 [592]
 [868]]


Pour les  fonctions de pertes ,elles se feront ulterieuement 
