In [8]:
import numpy as np
#illustration de l'addition et la soustraction matricielle avec le broacasting
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[7,8],[9,10],[11,12]])
print(f"(A+B)->{A+B}")
print(f"(A-B)->{A-B}")
#Multiplication avec un scaler 
D=A*0.2
print(f"(A*0.2)->{D}")
#multiplication element par element
M=A*B
print(f"(A*B)->{M}")
#notons que l'operateur * fait une multiplication element par element ,mais avec @ ou dot c'est le produit matricielle en tantque telle
p=A@B.T
dot=np.dot(A,B.T) 
if np.allclose(dot,p):
  print(f"c'est la meme chose entre dot et @")
else:
  print("c'est pas la meme chose ")

(A+B)->[[ 8 10]
 [12 14]
 [16 18]]
(A-B)->[[-6 -6]
 [-6 -6]
 [-6 -6]]
(A*0.2)->[[0.2 0.4]
 [0.6 0.8]
 [1.  1.2]]
(A*B)->[[ 7 16]
 [27 40]
 [55 72]]
c'est la meme chose entre dot et @


In [ ]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
W=np.random.randn(3,4)
b=np.random.randn(4)
#Caracteristiques des matrices
print(f"Matrice des entree: dim:{X.ndim}, shape:{X.shape}, nombre d'element:{X.size}")
print(f" Matrices de poids dim:{W.ndim}, Shape:{W.shape} , nombre d'element :{W.size}")
#calculs de produit matricielle , qui l'operation fondamentale d'un couche Dense
y=X@W+b
print(f"le produit matricielle suivit de l'ajout du biais avec le broadcasting :{y}")

print(f"tansposé de la matrice des poids:{W.T}")
print(f"le dimension de la matrice des poid:{W.T.shape}")


Matrice des entree: dim:2, shape:(4, 3), nombre d'element:12
 Matrices de poids dim:2, Shape:(3, 4) , nombre d'element :12
le produit matricielle suivit de l'ajout du biais avec le broadcasting :[[ -0.12030333  -2.11238112  -8.38235594  -4.85128365]
 [  1.27010081  -3.29974009 -15.53237923  -7.23925311]
 [  2.66050494  -4.48709906 -22.68240253  -9.62722256]
 [  4.05090907  -5.67445803 -29.83242583 -12.01519201]]
